export const CLASS_WORD_BANK: Record<string, string[]> = {
  LKG: [
    'cat', 'dog', 'hat', 'sun', 'bus', 'cup', 'pen', 'bag', 'ant', 'map',
    'fan', 'pot', 'mud', 'leg', 'arm', 'lip', 'fin', 'zip', 'jet', 'hug',
    'van', 'web', 'fog', 'gem', 'ivy', 'oak', 'pea', 'rye', 'tin', 'wax',
    'yam', 'bed', 'cot', 'den', 'ear', 'fig', 'gas', 'hop', 'ink', 'jam',
    'key', 'lad', 'mob', 'nap', 'orb', 'pad', 'rag', 'sap', 'tab', 'urn',
    'vim', 'wit', 'yak', 'zap', 'ace', 'bid', 'cue', 'dig', 'elf', 'fun',
    'gum', 'hem', 'ire', 'jot', 'keg', 'lid', 'mat', 'nod', 'opt', 'pod',
    'rep', 'set', 'top', 'use', 'vow', 'woe', 'yes', 'zoo', 'aim', 'bud',
    'cod', 'dew', 'eve', 'foe', 'gal', 'hew', 'ion', 'jaw', 'kin', 'lot',
    'men', 'nun', 'ode', 'pie', 'rim', 'sat', 'ten', 'vat', 'won', 'yet',
    'ale', 'bob', 'cob', 'axe', 'bat', 'box', 'boy', 'bye', 'cow', 'cry',
    'dry', 'dye', 'eat', 'egg', 'fly', 'fox', 'hen', 'ice', 'jar', 'kid',
    'kit', 'log', 'man', 'mix', 'net', 'new', 'nut', 'old', 'one', 'owl',
    'pig', 'pin', 'ram', 'rat', 'red', 'run', 'sad', 'saw', 'sea', 'sit',
    'sky', 'tea', 'toy', 'try', 'two', 'war', 'wet', 'who', 'win', 'bad',
    'big', 'bit', 'car', 'cop', 'cut', 'day', 'dot', 'end', 'far', 'fit',
    'fix', 'get', 'got', 'had', 'has', 'her', 'him', 'his', 'hot', 'how',
    'its', 'job', 'let', 'low', 'mad', 'may', 'met', 'mug', 'not', 'our',
    'out', 'pat', 'pet', 'pub', 'put', 'row', 'say', 'see', 'shy', 'sir',
    'son', 'sty', 'sub', 'tax', 'tie', 'ton', 'tub', 'tug', 'why', 'sip',
  ],
  UKG: [
    'ball', 'cake', 'rain', 'tree', 'fish', 'frog', 'star', 'moon', 'bird', 'book',
    'shoe', 'door', 'lamb', 'milk', 'rose', 'hill', 'road', 'lake', 'wind', 'sand',
    'fire', 'snow', 'leaf', 'iron', 'boat', 'duck', 'farm', 'gift', 'hand', 'jump',
    'kite', 'lamp', 'mice', 'nail', 'owl', 'play', 'quiz', 'ring', 'ship', 'tail',
    'ugly', 'vine', 'wall', 'yarn', 'zone', 'arch', 'bell', 'cave', 'dart', 'echo',
    'face', 'gate', 'herb', 'iris', 'jade', 'knot', 'lime', 'mist', 'nest', 'oath',
    'page', 'reed', 'seal', 'toad', 'urge', 'vale', 'wren', 'xray', 'yell', 'zinc',
    'acre', 'bale', 'corn', 'dune', 'earl', 'foam', 'gust', 'haze', 'jest', 'keen',
    'lark', 'mare', 'newt', 'opal', 'pave', 'rail', 'sage', 'tuft', 'unit', 'veal',
    'waft', 'yoga', 'zeal', 'aloe', 'brew', 'clay', 'dusk', 'edge', 'fawn', 'gnaw',
    'hull', 'inch', 'jury', 'acid', 'also', 'area', 'baby', 'back', 'band', 'bank',
    'bare', 'bark', 'base', 'beam', 'bean', 'bear', 'beat', 'belt', 'best', 'bill',
    'blow', 'blue', 'bold', 'bone', 'born', 'bowl', 'bulk', 'burn', 'bush', 'busy',
    'cafe', 'calm', 'camp', 'card', 'care', 'case', 'cast', 'chat', 'chef', 'city',
    'clan', 'claw', 'clip', 'club', 'coal', 'coat', 'code', 'coin', 'cold', 'cone',
    'cook', 'cool', 'cope', 'copy', 'cost', 'crew', 'crop', 'crow', 'cure', 'curl',
    'cute', 'dale', 'damp', 'dare', 'dash', 'data', 'date', 'dawn', 'dead', 'deal',
    'dear', 'debt', 'deck', 'deep', 'deer', 'desk', 'dial', 'diet', 'disc', 'dish',
    'dock', 'dome', 'done', 'dose', 'down', 'draw', 'drip', 'drop', 'drum', 'dual',
    'duke', 'dull', 'dust', 'duty', 'each', 'earn', 'ease', 'east', 'easy', 'envy',
  ],
  Class1: [
    'apple', 'bread', 'chair', 'drink', 'earth', 'flame', 'globe', 'heart', 'island', 'juice',
    'kings', 'light', 'magic', 'night', 'ocean', 'phone', 'queen', 'river', 'smoke', 'tiger',
    'under', 'voice', 'water', 'youth', 'zebra', 'amber', 'beach', 'cloud', 'dream', 'eagle',
    'fence', 'grape', 'honey', 'ivory', 'joker', 'kneel', 'lemon', 'mango', 'nerve', 'olive',
    'pearl', 'quest', 'raven', 'spice', 'emerald', 'tower', 'ultra', 'vivid', 'wheat', 'exact',
    'young', 'zippy', 'acorn', 'blaze', 'cedar', 'dwell', 'enter', 'flute', 'greet', 'house',
    'image', 'jewel', 'knack', 'lodge', 'mercy', 'noble', 'omega', 'prize', 'rocky', 'stone',
    'thyme', 'unite', 'verse', 'waste', 'xerox', 'yacht', 'ahead', 'bride', 'crisp', 'digit',
    'elbow', 'frail', 'giant', 'haste', 'ideal', 'jumpy', 'knave', 'laser', 'mason', 'nurse',
    'orbit', 'piano', 'rapid', 'sword', 'thumb', 'ulcer', 'windy', 'xeric', 'yield', 'azure',
    'about', 'above', 'actor', 'acute', 'admit', 'adopt', 'adult', 'after', 'again', 'agent',
    'agree', 'alarm', 'album', 'alert', 'alike', 'alive', 'allow', 'alone', 'along', 'alter',
    'among', 'anger', 'angle', 'angry', 'apart', 'apron', 'argue', 'arise', 'armed', 'armor',
    'arrow', 'aside', 'asset', 'audio', 'audit', 'avoid', 'award', 'awful', 'badge', 'badly',
    'baker', 'basic', 'basin', 'basis', 'batch', 'bath', 'beast', 'begin', 'being', 'below',
    'bench', 'berry', 'bible', 'birth', 'black', 'blade', 'blame', 'blank', 'blast', 'blend',
    'blind', 'blink', 'block', 'blood', 'bloom', 'board', 'boast', 'bonus', 'boost', 'bound',
    'brain', 'brand', 'brass', 'brave', 'break', 'breed', 'brick', 'brief', 'bring', 'broad',
    'broke', 'brown', 'brush', 'build', 'bunch', 'buyer', 'cabin', 'cable', 'camel', 'canal',
    'candy', 'cargo', 'carry', 'carve', 'cases', 'catch', 'cause', 'chase', 'cheat', 'check',
  ],
  Class2: [
    'absent', 'before', 'candle', 'danger', 'enough', 'frozen', 'garden', 'helper', 'custom', 'jungle',
    'kitten', 'locket', 'mirror', 'needle', 'offset', 'pillow', 'quirky', 'rubber', 'silver', 'topper',
    'unique', 'violet', 'wander', 'yellow', 'zipper', 'animal', 'basket', 'castle', 'dragon', 'energy',
    'finger', 'goblin', 'hunter', 'iguana', 'junior', 'knight', 'lizard', 'midday', 'napkin', 'orange',
    'parrot', 'rescue', 'saddle', 'target', 'unfair', 'velvet', 'winter', 'excite', 'zigzag', 'adjust',
    'butter', 'coffee', 'divide', 'expand', 'famous', 'garlic', 'handle', 'invite', 'joyful', 'kindly',
    'launch', 'method', 'narrow', 'oyster', 'puzzle', 'radius', 'sponge', 'triple', 'unpack', 'vacuum',
    'wallet', 'exceed', 'yelper', 'zodiac', 'arctic', 'bottom', 'crayon', 'dagger', 'effect', 'figure',
    'gravel', 'hornet', 'impact', 'jingle', 'kernel', 'lettuce', 'mosaic', 'nickel', 'option', 'paddle',
    'rocket', 'sketch', 'travel', 'accept', 'accord', 'across', 'action', 'active', 'actual', 'advice',
    'abroad', 'access', 'acting', 'admire', 'advise', 'afford', 'afraid', 'agency', 'agenda', 'agents',
    'agreed', 'almost', 'always', 'amount', 'anchor', 'angels', 'annual', 'answer', 'anyone', 'anyway',
    'appeal', 'appear', 'around', 'arrest', 'arrive', 'artist', 'aspect', 'assess', 'assist', 'assume',
    'attack', 'attend', 'autumn', 'avenue', 'backed', 'backup', 'barely', 'barrel', 'battle', 'beauty',
    'became', 'become', 'behalf', 'behind', 'belief', 'belong', 'berths', 'beside', 'better', 'beyond',
    'bishop', 'bitter', 'border', 'borrow', 'bottle', 'bought', 'bounce', 'branch', 'breeze', 'bridge',
    'bright', 'broken', 'bronze', 'bubble', 'bucket', 'budget', 'buffer', 'bullet', 'bundle', 'burden',
    'bureau', 'burner', 'bushy', 'button', 'buying', 'cabin', 'camera', 'campus', 'canyon', 'carbon',
    'career', 'carpet', 'carrot', 'casual', 'cattle', 'caught', 'center', 'chance', 'change', 'charge',
    'cheese', 'cherry', 'choice', 'choose', 'chorus', 'circle', 'circus', 'clause', 'clever', 'client',
  ],
  Class3: [
    'admiral', 'balance', 'captain', 'decline', 'enforce', 'freedom', 'grammar', 'harmony', 'imagine', 'journey',
    'kingdom', 'library', 'machine', 'natural', 'opinion', 'process', 'quarter', 'receive', 'service', 'through',
    'unusual', 'volcano', 'weather', 'examine', 'yearbook', 'almanac', 'benefit', 'cabinet', 'deliver', 'factory',
    'gesture', 'history', 'impulse', 'janitor', 'keyboard', 'lantern', 'mineral', 'outdoor', 'pattern', 'quality',
    'respond', 'shelter', 'tourist', 'uniform', 'village', 'wonder', 'eastern', 'younger', 'achieve', 'between',
    'climate', 'develop', 'forward', 'general', 'include', 'kitchen', 'learned', 'mention', 'nothing', 'outside',
    'perfect', 'require', 'section', 'usually', 'various', 'welcome', 'absence', 'certain', 'chapter', 'example',
    'growing', 'however', 'instead', 'keeping', 'looking', 'morning', 'nervous', 'opening', 'ability', 'academy',
    'account', 'accused', 'acquire', 'address', 'against', 'algebra', 'alliance', 'already', 'alright', 'amateur',
    'amazing', 'analyst', 'analyze', 'ancient', 'angrily', 'another', 'anxiety', 'anxious', 'anybody', 'applied',
    'abandon', 'abolish', 'absorb', 'abstract', 'accent', 'accepts', 'accident', 'acclaim', 'acidic', 'acreage',
    'actions', 'actively', 'activity', 'actress', 'actuals', 'adapter', 'adheres', 'adjunct', 'adjusts', 'admired',
    'admires', 'admitte', 'adopting', 'adoption', 'adoring', 'adorned', 'adsorb', 'advance', 'adverse', 'advises',
    'advisor', 'aerated', 'aerobic', 'aerosol', 'affects', 'affirm', 'afflict', 'affords', 'agencies', 'agendas',
    'agility', 'agitated', 'agonies', 'ailment', 'airbag', 'airfare', 'airless', 'airline', 'airmail', 'airport',
    'airship', 'airtight', 'alarmed', 'alchemy', 'alcohol', 'alcoves', 'alerted', 'aliases', 'alienate', 'aliens',
    'aligned', 'alimony', 'aliquot', 'allayed', 'alleged', 'alleles', 'allergy', 'allied', 'allower', 'alluded',
    'allure', 'almonds', 'altered', 'alumni', 'ambient', 'ambisex', 'amblers', 'ambling', 'amenity', 'amiable',
    'ammonia', 'amnesty', 'amongst', 'amusing', 'analogy', 'anchors', 'anchovy', 'anglers', 'angling', 'animals',
    'animate', 'annexed', 'annuity', 'answers', 'antagon', 'attempt', 'attract', 'average', 'avocado', 'awesome',
  ],
  Class4: [
    'absolute', 'boundary', 'complete', 'document', 'epidemic', 'fragment', 'guidance', 'heritage', 'incident', 'jealousy',
    'kindness', 'laughter', 'medicine', 'negative', 'occupied', 'personal', 'quantity', 'reliable', 'schedule', 'talented',
    'umbrella', 'variable', 'whenever', 'external', 'youthful', 'although', 'balanced', 'chemical', 'diameter', 'entrance',
    'faithful', 'grateful', 'hesitate', 'innocent', 'language', 'magnetic', 'novelist', 'obstacle', 'paradise', 'rational',
    'sentence', 'transfer', 'ultimate', 'virtually', 'whatever', 'yourself', 'abstract', 'birthday', 'calendar', 'describe',
    'evaluate', 'forecast', 'generate', 'homeless', 'identify', 'knockout', 'maintain', 'neighbor', 'original', 'position',
    'question', 'reaction', 'separate', 'thinking', 'universe', 'vacation', 'weakness', 'exercise', 'yearlong', 'altitude',
    'bursting', 'canceled', 'darkness', 'engineer', 'favorite', 'greatest', 'hospital', 'jubilant', 'launched', 'movement',
    'academic', 'accident', 'accuracy', 'accurate', 'achieved', 'acquiring', 'actively', 'activity', 'actually', 'addition',
    'adequate', 'adjacent', 'adjusted', 'advanced', 'advisory', 'advocate', 'affected', 'aircraft', 'allocate', 'allowing',
    'accepted', 'achiever', 'acquired', 'acquirer', 'additive', 'adhering', 'adjuster', 'admirers', 'admiring', 'admitted',
    'adoption', 'adorable', 'adorably', 'adornments', 'advocacy', 'aeration', 'aerators', 'aerobics', 'aerosols', 'aesthetic',
    'affinity', 'affirmed', 'affluent', 'afforded', 'aftermath', 'agonized', 'agrarian', 'airborne', 'airfields', 'airliner',
    'airlines', 'airports', 'airtight', 'alarmist', 'alchemists', 'alcohols', 'alerting', 'algebras', 'algebraic', 'alienated',
    'alienating', 'aligning', 'alignment', 'alkaline', 'alkaloid', 'alleging', 'allegiance', 'alliance', 'alluring', 'allusion',
    'alluvial', 'almanacs', 'alphabet', 'altering', 'alteration', 'altruism', 'altruist', 'aluminum', 'amateurs', 'amazement',
    'ambassador', 'ambergris', 'ambiance', 'ambition', 'ambitious', 'amenities', 'amicable', 'amicably', 'ammonia', 'ammonium',
    'amortize', 'amounted', 'amperage', 'amphibian', 'amplified', 'amplifier', 'amplitude', 'amputate', 'amputee', 'amusement',
    'analogous', 'analysis', 'analysts', 'analytic', 'analyzed', 'analyzer', 'anarchy', 'ancestor', 'anchored', 'anecdote',
    'angrily', 'animals', 'annually', 'answered', 'anxiously', 'anywhere', 'apparent', 'appealed', 'appeared', 'applying',
  ],
  Class5: [
    'accomplish', 'beneficial', 'celebration', 'democratic', 'elementary', 'fascinated', 'generosity', 'horizontal', 'illuminate', 'journalist',
    'knowledgeable', 'laboratory', 'mathematics', 'nomination', 'occupation', 'parliament', 'quarantine', 'responsible', 'suspension', 'technology',
    'understand', 'vegetation', 'wilderness', 'excellence', 'yesterday', 'admiration', 'brightness', 'commentary', 'discovered', 'endangered',
    'fellowship', 'graduation', 'hospitality', 'imaginary', 'kidnapper', 'luminosity', 'mysterious', 'nationwide', 'opposition', 'production',
    'rhinoceros', 'sensitivity', 'tournament', 'unjustified', 'validation', 'wandering', 'expedition', 'younglings', 'anthology', 'bankruptcy',
    'capitalism', 'democracy', 'equipment', 'formation', 'guideline', 'hibernate', 'isolation', 'judgement', 'kilometer', 'liberation',
    'memoranda', 'negotiate', 'obscurity', 'patriotism', 'quarterly', 'rationale', 'substance', 'testimony', 'uppercase', 'variation',
    'workmanship', 'xenophobe', 'zoologist', 'architect', 'breakfast', 'colleague', 'dashboard', 'eagerness', 'flagpole', 'gymnasium',
    'abundance', 'accessible', 'accidentally', 'accommodate', 'accompanied', 'accordance', 'accounting', 'accumulate', 'accurately', 'accusation',
    'accustomed', 'activities', 'adaptation', 'additional', 'adequately', 'adjustment', 'administer', 'admissions', 'admittance', 'adolescent',
    'academics', 'accelerate', 'acceptable', 'acceptance', 'accidental', 'acclaiming', 'accolated', 'accompanying', 'accountant', 'achievable',
    'acidifying', 'adherence', 'adhesives', 'adjectival', 'adjustable', 'admissibility', 'adornments', 'advantages', 'adventurer', 'adventures',
    'adversaries', 'adversity', 'advertiser', 'advertising', 'advisable', 'advisory', 'advocating', 'aerating', 'aeration', 'aesthetics',
    'affecting', 'affection', 'affiliate', 'affirmative', 'affliction', 'affordability', 'afternoon', 'aggressively', 'agitations', 'agreeable',
    'agreements', 'agricultural', 'airdropped', 'alarmingly', 'alchemists', 'algorithms', 'alienation', 'alignments', 'allegation', 'allegiances',
    'alleviation', 'allotments', 'allowances', 'alternatives', 'altogether', 'altruistic', 'ambassadors', 'ambiguous', 'ambitions', 'ambitiously',
    'ambivalent', 'amenities', 'ammunition', 'amorphous', 'amplification', 'amplifying', 'amusements', 'anachronism', 'analogous', 'analytical',
    'analyzers', 'anarchists', 'ancestors', 'ancestry', 'anchorage', 'anecdotal', 'anesthetic', 'angrily', 'animation', 'animosity',
    'anniversary', 'announcing', 'annoyance', 'anonymous', 'antagonist', 'antibodies', 'anticipate', 'government', 'responsibility', 'environment',
    'independent', 'development', 'information', 'management', 'understanding', 'significant', 'relationship', 'association', 'performance', 'professional',
  ],
  Class6: [
    'abbreviation', 'collaboration', 'determination', 'electromagnetic', 'fragmentation', 'generalization', 'humanitarian', 'identification', 'justification', 'kaleidoscope',
    'liberalization', 'magnetosphere', 'nationalization', 'organization', 'philanthropist', 'qualification', 'rationalization', 'spectacular', 'telecommunications', 'unauthorized',
    'vulnerability', 'westernization', 'xenophobia', 'anniversary', 'bureaucracy', 'civilization', 'deforestation', 'elaboration', 'fluctuation', 'globalization',
    'hydroelectric', 'illustration', 'jurisdiction', 'laceration', 'manifestation', 'neutralization', 'optimization', 'persecution', 'quantification', 'realization',
    'sterilization', 'transportation', 'urbanization', 'vaporization', 'weatherization', 'exaggeration', 'yellowish', 'zoomorphism', 'acceleration', 'bifurcation',
    'catastrophe', 'depreciation', 'enlightenment', 'fluorescent', 'gravitational', 'horizontally', 'industrialize', 'jellyfish', 'kindergarten', 'luminescence',
    'monochromatic', 'navigation', 'observation', 'procurement', 'revolutionary', 'sophisticated', 'terminology', 'underprivileged', 'visualization', 'extraordinary',
    'yardstick', 'zigzagged', 'abolitionist', 'accelerator', 'accentuating', 'acceptability', 'accessibility', 'accompanying', 'accomplishing', 'accumulations',
    'acquaintances', 'adaptability', 'addressing', 'adjustments', 'administration', 'administrative', 'advisability', 'affectionately', 'affiliations', 'aggregations',
    'agricultural', 'air-conditioning', 'alignments', 'alternatives', 'ambassadors', 'ambiguities', 'amelioration', 'ammunition', 'amplifications', 'amusements',
    'academician', 'accelerating', 'accessories', 'accidentally', 'acclimatized', 'accommodated', 'accommodates', 'accompaniment', 'accomplished', 'accomplishes',
    'accountability', 'accumulated', 'accumulative', 'accusatorial', 'acknowledging', 'acquisitions', 'adventurers', 'adventurous', 'adversaries', 'advocating',
    'aerodynamics', 'affectionate', 'agglomeration', 'aggression', 'allegations', 'alleviation', 'alternating', 'amalgamated', 'ambitious', 'ambivalence',
    'ameliorated', 'amplification', 'anachronistic', 'analogies', 'analytical', 'anarchistic', 'ancestors', 'anchorages', 'anecdotes', 'anesthesiology',
    'angrily', 'animated', 'annihilation', 'annotations', 'announcements', 'annoyance', 'anonymous', 'antagonism', 'antagonist', 'anticipation',
    'anticipatory', 'antiseptics', 'anxieties', 'apologizing', 'apparatus', 'apparel', 'apparent', 'appealable', 'appearance', 'appetizers',
    'appliances', 'applicable', 'applications', 'appointed', 'appointment', 'appreciable', 'appreciated', 'appreciates', 'apprehension', 'apprentice',
    'approaches', 'approaching', 'appropriate', 'approval', 'approving', 'approximate', 'arbitrarily', 'arbitration', 'architects', 'architecture',
    'archives', 'argumentative', 'arrangements', 'arrested', 'arrivals', 'arrogance', 'articulates', 'artificial', 'artistic', 'government',
    'responsibility', 'environment', 'independent', 'development', 'information', 'management', 'understanding', 'significant', 'relationship', 'association',
  ],
  Class7: [
    'abominable', 'benevolence', 'camaraderie', 'deliberation', 'fluorescence', 'hallucination', 'incomprehensible', 'juxtaposition', 'kaleidoscopic', 'metamorphosis',
    'nanotechnology', 'ostentatious', 'perpendicular', 'quintessential', 'serendipitous', 'telecommunication', 'unprecedented', 'vivisection', 'whimsical', 'exacerbation',
    'youthfulness', 'anachronism', 'biodiversity', 'circumference', 'deterioration', 'electrolysis', 'functionality', 'hypothetical', 'inconsistency', 'kinematics',
    'lamentation', 'magnification', 'neurological', 'photosynthesis', 'reactionary', 'stratospheric', 'thermodynamic', 'underpinning', 'worldliness', 'xenomorphic',
    'yellowstone', 'approximation', 'bureaucratic', 'claustrophobia', 'deconstruction', 'expropriation', 'flamboyance', 'geopolitical', 'hieroglyphics', 'imperialism',
    'monopolization', 'non-conformist', 'orchestration', 'precipitation', 'reverberation', 'sophistication', 'translucency', 'ubiquitousness', 'vaccination', 'aberration-rate',
    'acclimatized', 'accommodationist', 'accompaniments', 'accomplishments', 'accountability', 'accumulations-net', 'acknowledgements', 'acquiescence', 'activations', 'adaptabilities',
    'additionally-well', 'administrated', 'admissibility', 'advantageous', 'advertisements', 'advisability-test', 'advocacy-group', 'aeronautical', 'aestheticism', 'affectation-show',
    'afforestation', 'after-effects', 'agglomeration', 'agreeableness', 'agriculturally', 'alleviation', 'alliterations', 'alluvial-plains', 'alternating-current', 'amalgamation',
    'ambassadorial', 'ambiguity-check', 'ambitiousness', 'ambivalence', 'amortization', 'amphitheaters', 'amplification', 'anachronistic-use', 'anagrammatical', 'analogical-maps',
    'aberration', 'abolitionist', 'acclimatization', 'accommodation', 'accompanist', 'accomplice', 'accumulation', 'acknowledgement', 'acquaintance', 'acquisition',
    'adaptability', 'addressing', 'administration', 'administrative', 'adolescence', 'advertisement', 'alliteration', 'amphitheater', 'anagrammatic', 'analogical',
    'analysis', 'anarchism', 'anesthetist', 'angularity', 'annihilation', 'announcement', 'anthropologist', 'anticipation', 'antipathy', 'antiquarian',
    'apologetically', 'apparatus-set', 'appeal-court', 'appearance-check', 'apprehensive', 'apprenticeship', 'appropriateness', 'archaeological', 'architectural', 'aristocracy',
    'arithmetician', 'arrangement', 'articulation', 'artificiality', 'assassination', 'assemblage', 'assignment', 'assimilation', 'association', 'astonishment',
    'astronomical', 'atmosphere', 'attachment', 'attainment', 'attendance', 'attentiveness', 'attestations', 'attractiveness', 'authenticities', 'authoritative',
    'authorization', 'autobiography', 'availability', 'back-pedaling', 'background', 'bacteriologist', 'balance-sheet', 'barbarously', 'beneficiary', 'benevolent',
    'bibliography', 'biochemistry', 'biodegradable', 'biographical', 'biosphere', 'bitterness', 'blacklisting', 'boundary-line', 'breathlessness', 'bureaucracy',
    'calculation', 'calibration', 'government', 'responsibility', 'environment', 'independent', 'development', 'information', 'management', 'understanding',
    'significant', 'relationship', 'performance', 'professional', 'communication', 'opportunity', 'possibility', 'organization', 'personality', 'construction',
  ],
  Class8: [
    'abhorrence', 'bibliographic', 'circumstantial', 'discombobulate', 'ecclesiastical', 'fluoridation', 'gastrointestinal', 'hematological', 'incompatibility', 'jurisprudential',
    'laryngeal', 'metamorphic', 'nomenclature', 'osteogenesis', 'paleontological', 'quaternary', 'rhetorical', 'seismological', 'thermochemical', 'ultrasonography',
    'running-actions', 'anachronistic', 'biogeochemical', 'chemosynthesis', 'disenfranchise', 'epidemiological', 'geomorphological', 'hydrodynamical', 'immunodeficiency', 'jurisdictional',
    'kinesthetically', 'lymphocytopenia', 'morphologically', 'neuropharmacology', 'ophthalmological', 'pathophysiology', 'quantitatively', 'radiochemistry', 'socioeconomical', 'thermodynamically',
    'ultraviolet', 'vulcanological', 'waterlogged', 'xenobiotic', 'aesthetics', 'bibliophilia', 'categorization', 'deliberateness', 'electromagnetics', 'fluctuations',
    'gravitationally', 'hierarchically', 'interdisciplinary', 'judiciously', 'kinematography', 'mythologically', 'naturalization', 'osteoarthritis', 'pharmaceutical', 'qualitatively',
    'reconfiguration', 'sociolinguistic', 'transmogrification', 'vandalization', 'weatherproofing', 'xerography', 'abhorring-actions', 'academician', 'acclimatizations', 'accommodating-space',
    'accomplishing-tasks', 'accordance-level', 'accountability-check', 'accoutrements', 'accreditations', 'accumulating-snow', 'acknowledging-help', 'acoustician', 'acquaintanceship', 'acquiescingly-quietly',
    'acquisitiveness', 'acrimoniousness', 'actuarial-math', 'acupuncture-clinic', 'adaptability-test', 'addressable-space', 'adequateness', 'administering-med', 'administrations-net', 'admiringly-saying',
    'admissibilities', 'admonishments', 'adolescence-stage', 'adoptability-check', 'adorability-show', 'adulterations', 'advantageousness', 'adventurously', 'abbreviation', 'absolute-zero',
    'abstract-nature', 'academicians', 'accelerations', 'acceptabilities', 'acceptableness', 'accessibilities', 'accessible-path', 'accidentalness', 'accommodations', 'accompaniments',
    'accomplishments', 'accountabilities', 'accumulations', 'acknowledgements', 'acousticians', 'acquaintanceships', 'acquiescences', 'adaptabilities', 'adaptiveness', 'addressability',
    'adequatenesses', 'administrations', 'adolescent-phase', 'adoptabilities', 'adorablenesses', 'adventurousness', 'adversities', 'advertisements', 'advisabilities', 'aeronautics',
    'aesthetic-value', 'affectations', 'affiliations', 'afforestation', 'after-thoughts', 'agglomerations', 'agreeablenesses', 'agriculturalists', 'air-conditioner', 'alignments-net',
    'alliterations', 'alluvial-plains', 'amalgamations', 'ambassadorial-car', 'ambition-level', 'ambitiousnesses', 'ambivalences', 'ameliorations', 'ammunition-dump', 'amphitheaters',
    'amplifications', 'anachronisms', 'anagrammatic-use', 'analogical-maps', 'analytical-tools', 'anarchistically', 'anesthesiologist', 'angular-momentum', 'annihilations', 'announcements-board',
    'anthropologists', 'anticipations', 'antidepressants', 'antipathetic', 'antiquated-look', 'apologetically-said', 'apparatus-design', 'appearances-show', 'applicabilities', 'apprehensiveness',
    'apprenticeships', 'appropriatenesses', 'approximations', 'archaeologists', 'architectural-art', 'aristocracies', 'arithmeticians', 'arrangements-net', 'articulatenesses', 'artificialities',
    'assassinations', 'assemblages-net', 'assignments-due', 'assimilations', 'associations-net', 'astonishments', 'astronomical-units', 'atmospheric-air', 'attachments-net', 'attainablenesses',
    'attendances-sheet', 'attentivenesses', 'attestations', 'attractivenesses', 'authenticities', 'authoritativeness', 'authorizations', 'autobiographies', 'availabilities', 'government',
  ],
  Class9: [
    'abdominoplasty', 'bioelectromagnetics', 'chemiluminescence', 'deoxyribonucleic', 'electroencephalography', 'fluorodeoxyglucose', 'gastroenterologist', 'hematochromatosis', 'immunohistochemistry', 'jurisprudence',
    'focus-words', 'lymphadenopathy', 'magnetohydrodynamics', 'neuropharmacological', 'ophthalmoscopy', 'pneumonoultramicroscopicsilicovolcanoconiosis', 'rhinolaryngoscopy', 'spectrophotometric', 'thermoluminescence', 'ventriculoperitoneal',
    'wholeheartedness', 'extracorporeal', 'xeroradiography', 'adenocarcinomatous', 'bioremediation', 'cinematography', 'democratization', 'electrocardiogram', 'fluoroscopy', 'geomorphodynamics',
    'hydrochlorofluorocarbon', 'interdisciplinarity', 'kinesiotherapy', 'lymphangioleiomyomatosis', 'magnetoencephalography', 'nanotribological', 'oligodendroglioma', 'paraphernalia', 'sociolinguistics', 'ultrasound',
    'vasoconstriction', 'xenotransplantation', 'yellowcake', 'authorization', 'bibliographical', 'chronobiological', 'dermatoglyphics', 'electrophometrically', 'fluorobenzene', 'gastroenterological',
    'hemorrhagic', 'immunocompromised', 'laryngopharyngeal', 'focus-phonics', 'oligophrenia', 'pharmacokinetics', 'quantitatively', 'radiopharmaceutical', 'steganography', 'thermoreceptor',
    'ultracentrifugation', 'relativewords', 'wavelengths', 'abdominally-focused', 'academician-group', 'accelerations-list', 'acceptabilities', 'acceptableness', 'accessibilities', 'accessible-routes',
    'accidentalness', 'acclimatizations-net', 'accommodatingly', 'accompanist-player', 'accomplished-goal', 'accordance-levels', 'accountabilities', 'accoutrements-kit', 'accreting-materials', 'accretionary-prism',
    'accumulatively', 'accurateness-level', 'accusations-flown', 'accustomed-manner', 'acetylcholinesterase', 'achievabilities', 'achievableness', 'acknowledgements-page', 'acknowledging-gifts', 'acousticians',
    'acquaintanceships', 'acquiescingly-done', 'acquisitive-nature', 'acrimoniousnesses', 'acrobatics-troupe', 'actionability-check', 'activational-force', 'actualizations', 'adaptabilities-test', 'adaptableness-grade',
    'adaptively-managed', 'additional-problems', 'adequately-prepared', 'adhesiveness-rating', 'adjectivally-used', 'adjudications', 'administering-tests', 'administrative-task', 'admirableness', 'admissibilities',
    'admonitory-speech', 'adolescents-group', 'adoptability-rate', 'adoptiveness-scale', 'adorablenesses', 'adornments-list', 'adrenalectomized', 'adventurously-run', 'adversaria-files', 'advertisements-run',
    'advisability-grades', 'advocacy-groups', 'aeronautical-maps', 'aesthetician-salon', 'affectedly-spoken', 'affiliations-list', 'afforestation-net', 'after-dinner-speech', 'agglomerations-net', 'agreeablenesses',
    'agricultural-fields', 'air-conditioned-bus', 'alignments-matrix', 'alliterations-list', 'alluvial-deposits', 'alternating-currents', 'amalgamations-list', 'ambassadorial-staff', 'ambiguity-matrices', 'ambitiousnesses',
    'ambivalent-feelings', 'ameliorations-list', 'ammunition-stores', 'amphitheaters-list', 'amplifications-list', 'anachronistically', 'anagrammatic-words', 'analogical-models', 'analytical-methods', 'anarchistically-run',
    'anesthesiology-dept', 'angular-momentums', 'annihilations-list', 'announcement-boards', 'anthropologists-list', 'anticipation-levels', 'antidepressants-list', 'antipathetic-stance', 'apologetic-letters', 'apparatus-designs',
    'appearances-rating', 'applicability-tests', 'apprehensivenesses', 'apprenticeship-term', 'appropriatenesses', 'approximations-list', 'archaeologists-group', 'architectural-plans', 'aristocratic-family', 'arithmetician-group',
    'arrangements-board', 'articulatenesses', 'artificial-intelligences', 'assassinations-list', 'assemblages-matrix', 'assignments-marks', 'assimilations-matrix', 'association-ratings', 'astonishments-list', 'astronomical-charts',
    'atmospheric-pressure', 'attachments-list', 'attainability-check', 'attendances-matrix', 'attentiveness-rating', 'attestations-list', 'attractiveness-scale', 'authenticities-check', 'authoritativenesses', 'authorizations-list',
    'autobiographical-net', 'availabilities-list', 'avalanche-warning', 'government', 'responsibility', 'environment', 'independent', 'development', 'information', 'management',
  ],
  Class10: [
    'abdominoperitoneal', 'deoxyribonucleoprotein', 'electroencephalographic', 'gastroenterostomy', 'immunoelectrophoresis', 'jurisprudentially', 'lymphadenocarcinoma', 'magnetohydrodynamical', 'neuropsychopharmacology', 'ophthalmodynamometry',
    'pseudohypoparathyroidism', 'radioimmunoscintigraphy', 'spectrophotometrical', 'thermonucleodynamics', 'ultrasonographically', 'vasoconstrictor', 'extraterritoriality', 'xeroradiographically', 'adenohypophyseal', 'bioelectrogenesis',
    'cinematographically', 'electrocardiographically', 'fluororeticulate', 'geomorphodynamical', 'hydrochlorofluorocarbons', 'interdisciplinarily', 'jurisconsultation', 'kinesiologically', 'lymphangiomyomatosis', 'magnetoencephalographically',
    'nanoelectromechanical', 'oligodendrogliomatous', 'pharmacotherapeutical', 'radiopharmaceutically', 'sociodemographically', 'xenotransplantational', 'greyhound-racing', 'dermatoglyphic', 'electroplethysmography', 'fluorhydrocarbon',
    'gastroparesis', 'hemispherectomy', 'immunoprecipitation', 'jurisdictionally', 'morphogenetically', 'oligophrenic', 'steganographically', 'thermoregulation', 'ultracentrifugationally', 'vivisectional',
    'xerographically', 'yottabyte', 'zygomorphic', 'abdominally-treated', 'academician-status', 'accelerators-list', 'acceptableness-rate', 'accessibilities-test', 'acclimatized-animal', 'accommodating-space-total',
    'accompanist-audition', 'accomplished-musician', 'accountability-standards', 'accoutrements-uniform', 'accreting-matter-system', 'accretionary-processes', 'accumulative-benefits', 'accuratenesses', 'accusatorial-system', 'accustomed-traditions',
    'acetylcholinesterases', 'achievablenesses', 'acknowledgements-section', 'acquaintanceship-term', 'acquiescently-agreed', 'acquisitiveness-trait', 'acrimoniously-spoken', 'acrobatics-champions', 'actionabilities', 'activation-energies',
    'actualization-process', 'adaptabilities-grades', 'adaptableness-matrix', 'adaptively-controlled', 'addressability-matrix', 'adhesiveness-ratings', 'adjectivally-modified', 'adjudication-hearings', 'administering-officer', 'administrative-duties',
    'admirablenesses', 'admissibility-rulings', 'admonitory-remarks', 'adolescents-behavior', 'adoptabilities-rating', 'adoptiveness-factors', 'adorablenesses-visual', 'adornments-decorations', 'adrenalectomies', 'adventurousness-index',
    'adventurously-acting', 'adversaria-documents', 'advertisements-campaign', 'advisability-standards', 'advocacy-group-leader', 'aeronautical-engineer', 'aesthetician-techniques', 'affectedly-speaking-loud', 'affiliations-directory', 'afforestation-programs',
    'after-dinner-speeches-list', 'agglomerations-standards', 'agreeableness-index', 'agricultural-departments', 'air-conditioned-buses-list', 'alignments-matrix-system', 'alliterations-examples-list', 'alluvial-plain-deposits', 'alternating-current-motors', 'amalgamations-procedures',
    'ambassadorial-representatives', 'ambiguity-matrices-results', 'ambitiousness-indicators', 'ambivalent-feelings-total', 'ameliorations-standards', 'ammunition-stores-control', 'amphitheaters-designs-list', 'amplifications-matrices', 'anachronistically-spoken', 'anagrammatic-words-finder',
    'analogical-models-mapping', 'analytical-methods-testing', 'anarchistically-oriented', 'anesthesiology-department', 'angular-momentum-equations', 'annihilations-processes', 'announcement-boards-display', 'anthropologists-discoveries', 'anticipation-levels-metrics', 'antidepressants-prescribed',
    'antipathetic-stance-taken', 'apologetic-letters-written', 'apparatus-designs-testing', 'appearances-rating-matrix', 'applicability-tests-grades', 'apprehensivenesses-total', 'apprenticeship-terms-ends', 'appropriatenesses-matrix', 'approximations-algorithms', 'archaeologists-excavations',
    'architectural-plans-house', 'aristocratic-families-list', 'arithmetician-group-members', 'arrangements-board-setup', 'articulatenesses-standards', 'artificial-intelligence-list', 'assassinations-historical', 'assemblages-matrix-systems', 'assignments-marks-database', 'assimilations-matrix-charts',
    'association-ratings-report', 'astonishments-occurrences', 'astronomical-charts-mapping', 'atmospheric-pressure-gauge', 'attachments-list-documents', 'attainability-check-scales', 'attendances-matrix-sheets', 'attentiveness-rating-scales', 'attestations-list-signatures', 'attractiveness-scale-marks',
    'authenticities-check-reports', 'authoritativeness-metrics', 'authorizations-list-granted', 'autobiographical-novel-list', 'availabilities-list-updated', 'avalanche-warning-systems', 'government', 'responsibility', 'environment', 'independent',
    'development', 'information', 'management', 'understanding', 'significant', 'relationship', 'association', 'performance', 'professional', 'communication',
    'opportunity', 'possibility', 'organization', 'personality', 'construction', 'distribution', 'conversation', 'satisfaction', 'presentation', 'determination',
  ],
  Class11: [
    'antiestablishmentarianism', 'floccinaucinihilipilification', 'honorificabilitudinitatibus', 'pneumonoultramicroscopicsilicovolcanoconiosis', 'sesquipedalianism', 'supercalifragilisticexpialidocious', 'pseudopseudohypoparathyroidism', 'antidisestablishmentarianism', 'incomprehensibilities', 'unconstitutionalities',
    'spectrofluorophotometrically', 'psychoneuroimmunology', 'electrocardiographically', 'immunoelectrophoretically', 'trichotillomania', 'dacryocystorhinostomy', 'otorhinolaryngological', 'encephalomyocarditis', 'pancreatoduodenectomy', 'hysterosalpingography',
    'magnetohydrodynamically', 'counterrevolutionary', 'interdisciplinary', 'uncharacteristically', 'disproportionately', 'indistinguishable', 'misrepresentation', 'undocumentable', 'autobiographical', 'circumstantiality',
    'multidimensional', 'hydroclimatology', 'nanobiotechnology', 'spectroheliograph', 'thermodynamically', 'paleoclimatology', 'hyperbilirubinemia', 'histocompatibility', 'parathyroidectomy', 'cholecystectomy',
    'electrocoagulation', 'neurodegenerative', 'ultracentrifuge', 'vasoconstrictive', 'bronchoconstriction', 'endocrinological', 'epistemological', 'phenomenological', 'transcendentalism', 'existentialism',
    'deconstructionism', 'hermeneutical', 'historiographical', 'intertextuality', 'multilateralism', 'microeconomics', 'macroeconomics', 'counterintelligence', 'decommissioning', 'cryptographically',
    'biodegradability', 'parasitological', 'pharmacological', 'toxicological', 'epidemiological', 'meteorological', 'seismologically', 'volcanologically', 'crystallographic', 'spectroscopically',
    'interferometer', 'chromatographical', 'electrochemical', 'thermoelectrical', 'piezoelectrical', 'pyroelectrical', 'superconducting', 'semiconducting', 'ferroelectrical', 'electromagnetic',
    'gravitationally', 'astrophysically', 'cosmologically', 'paleontological', 'paleoanthropology', 'archaeomagnetism', 'dendrochronology', 'biogeochemical', 'photosynthetic', 'chemosynthetic',
    'organometallic', 'macromolecular', 'stereochemical', 'stereoisomerism', 'enantiomeric', 'diastereomeric', 'constitutional', 'conformational', 'regioselectivity', 'stereoselectivity',
    'enantioselectivity', 'biocompatibility', 'biodistribution', 'pharmacokinetic', 'pharmacodynamic', 'immunogenicity', 'histopathological', 'pathophysiology', 'electroencephalogram', 'electromyographical',
    'electroretinogram', 'electrooculogram', 'polysomnography', 'echocardiography', 'ultrasonography', 'fluoroscopically', 'bronchoscopy', 'colonoscopically', 'sigmoidoscopy', 'gastroduodenoscopy',
    'laparoscopically', 'thoracoscopically', 'mediastinoscopy', 'arthroscopically', 'angioplasty', 'atherectomy', 'thrombectomy', 'embolization', 'chemoembolization', 'radioembolization',
    'brachytherapy', 'immunotherapeutic', 'biotechnologically', 'nanotechnology', 'microfluidics', 'optoelectronics', 'spintronics', 'nanophotonics', 'plasmonics', 'metamaterials',
    'superlattices', 'heterostructures', 'photolithography', 'electron-beam', 'magnetron-sputter', 'electrospinning', 'sol-gel-process', 'chemical-vapor', 'physical-vapor', 'hydrothermally',
    'monocrystalline', 'polycrystalline', 'amorphous-silicon', 'organphosphorus', 'organchlorine', 'carbamate-pesticide', 'pyrethroid-pesticide', 'neonicotinoid', 'bioaccumulation', 'biomagnification',
    'eutrophication', 'acidification', 'desertification', 'deforestation', 'urbanization', 'suburbanization', 'gentrification', 'industrialization', 'globalization', 'transnationalism',
    'postmodernism', 'structuralism', 'poststructuralism', 'psychoanalytical', 'behavioral-science', 'cognitive-science', 'neurobiology', 'neuroanatomy', 'neurochemistry', 'neurophysiology',
    'neuropsychology', 'psychopathology', 'psychopharmacology', 'psychosomatic', 'somatoform-disorder', 'schizophrenia', 'manic-depressive', 'neurotic-disorder', 'psychotic-disorder', 'gastroenterology',
    'hepatology', 'nephrology', 'urology', 'gynecology', 'obstetrics', 'neonatology', 'pediatrics', 'geriatrics', 'oncology', 'hematology',
  ],
};
